---
title: "Détecteur de lecteur inattendu"
output:
  flexdashboard::flex_dashboard:
    storyboard: true
params:
  periode_start: !r as.Date("2017-01-01")
  periode_end: !r Sys.Date()
  url: http://chrhc.revues.org/1907

  
  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(highcharter)
library(memoise)
library(detectR)
library(dplyr)
```

```{r memoise}
m_get_visits <- memoise(get_visits, cache = fc)
```


### Combien de lecteurs inattendus ?

```{r}

df_visites <- m_get_visits(params$url, 
           from = params$periode_start,
           to = params$periode_end,
           backend = tbl_all_actions)
df_visites <- xts::xts(df_visites$n, order.by = df_visites$date)

df_anomalies <- anomalies %>% 
  filter(url %in% params$url) %>% 
  mutate(title = "!", text = "Épisode de lecteurs inattendus")
# df_anomalies <- xts::xts(df_anomalies$real_visitors, order.by = df_anomalies$date)




highchart(type = "stock") %>%
  hc_add_series(df_visites, id = "visites") %>%
  hc_add_series(df_anomalies, hcaes(x = date), type = "flags", onSeries = "visites")


```



### Que sait-on du document concerné ?

### D'où viennent les lecteurs inattendus ? 


